### ISSUE TITLE
It is great guide. 

### ISSUE THREAD

**Issue by antranvn** [erikcaffrey/Movies-PagingLibrary-Arch-Components#3]
But what happen if user delete picture

**Comment by erikjhordan-rey** [comment]
It's a good question since PageList is immutable, I think was designed to use room library so you can delete/update an item and the dataset will be updated automatically. Without Room maybe you could do it but using some hacks. 


Read more -> https://github.com/googlesamples/android-architecture-components/issues/281

**Comment by memocostecho** [comment]
@antranvn @erikjhordan-rey I am currently implementing pagination without room and I was able to solve the problem of altering the DataSource using a DataSource.Factory as the Documentation suggests [https://developer.android.com/reference/kotlin/androidx/paging/DataSource#updating-paged-data](doc) and not needing to use Room only for this use case, I can provide more details if you need them.

**Comment by dzboot02** [comment]
@memocostecho can you please provide more info on how to implement that?

**Comment by antranvn** [comment]
@memocostecho, thank you but as far as i know Room is the brilliant solution which is supported by great Jetpack team.
